VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  boxes = [
    { :name => "ubuntu-test-box", :box => "generic/ubuntu1804" },
    { :name => "centos-test-box", :box => "generic/centos7" }
  ]
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = opts[:box]
      config.ssh.forward_agent = true
      config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
      config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "test.yml"
          ansible.limit = "all"
        end
      end
    end
  end
end


# Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#   config.vm.box = "generic/ubuntu1804"
#   config.ssh.forward_agent = true
#   config.vm.network "forwarded_port", guest: 80, host: 8080
#   config.vm.network "forwarded_port", guest: 443, host: 8443
#   config.vm.provision "ansible" do |ansible|
#     ansible.playbook = "/home/sergeys/repo/roles/install_nginx/tests/test.yml"
#     ansible.limit = "all"
#   end  
# end